CREATE TABLE "HFLUMIRESULT"
(	"RUNNUM" NUMBER(10,0) NOT NULL ENABLE,
	"LUMI" NUMBER(10,0) NOT NULL ENABLE,
	"LUMI_CMS" NUMBER(10,0) NOT NULL ENABLE,
	"FILLNUM" NUMBER(10,0) NOT NULL ENABLE,
	"TIME" TIMESTAMP(6) NOT NULL ENABLE,
	"BEAM_STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"ENERGY" NUMBER(10,0) NOT NULL ENABLE,
     	"DELIVERED" BINARY_FLOAT, 
        "AVG_PU" BINARY_FLOAT,
        "DATA_VERSION" VARCHAR2(50) NOT NULL ENABLE,
	"NORM_VERSION" VARCHAR2(50) NOT NULL ENABLE,
        "INSERT_TIME" TIMESTAMP NOT NULL ENABLE DEFAULT SYSDATE,
	CONSTRAINT "HFLUMIRESULT_PK" PRIMARY KEY ("RUNNUM","LUMI")
)
PARTITION BY RANGE(RUNNUM)
(
PARTITION YEAR2010 VALUES LESS THAN(153368),
PARTITION YEAR2011 VALUES LESS THAN(183338),
PARTITION THEREST VALUES LESS THAN(MAXVALUE)
)
