/*=========================LUMICORRECTIONS=======================*/
begin execute immediate 'drop table LUMICORRECTIONS';exception when others then null;end;
CREATE TABLE "LUMICORRECTIONS"
("NAME" VARCHAR2(128),
"A1" BINARY_FLOAT,
"A2" BINARY_FLOAT,
"DRIFT" BINARY_FLOAT,
"ISDEFAULT" NUMBER(10,0),
CONSTRAINT "LUMICORRECTIONS_PK" PRIMARY KEY ("NAME")
);
GRANT SELECT ON "LUMICORRECTIONS" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS" TO CMS_LUMI_WRITER;
