/*=========================LUMICORRECTIONS=======================*/
CREATE TABLE "LUMICORRECTIONS"
(
"DATA_ID"  NUMBER(20,0),
"ENTRY_ID" NUMBER(20,0),
"ENTRY_NAME" VARCHAR2(56),
"A1" BINARY_FLOAT,
"A2" BINARY_FLOAT,
"DRIFT" BINARY_FLOAT,
CONSTRAINT "LUMICORRECTIONS_PK" PRIMARY KEY ("DATA_ID")
);
GRANT SELECT ON "LUMICORRECTIONS" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS" TO CMS_LUMI_WRITER;

/*=========================LUMICORRECTIONS_ID=======================*/
CREATE TABLE "LUMICORRECTIONS_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "LUMICORRECTIONS_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "LUMICORRECTIONS_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "LUMICORRECTIONS_ID" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS_ID" TO CMS_LUMI_WRITER;

/*=========================LUMICORRECTIONS_ENTRIES=======================*/
CREATE TABLE "LUMICORRECTIONS_ENTRIES"
(	"ENTRY_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	"NAME" VARCHAR2(56),
	 CONSTRAINT "LUMICORRECTIONS_ENTRIES_PK" PRIMARY KEY ("ENTRY_ID")
);
GRANT SELECT ON "LUMICORRECTIONS_ENTRIES" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS_ENTRIES" TO CMS_LUMI_WRITER;
/*=========================LUMICORRECTIONS_ENTRIES_ID=======================*/
CREATE TABLE "LUMICORRECTIONS_ENTRIES_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "LUMICORRECTIONS_ENTRIES_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "LUMICORRECTIONS_ENTRIES_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "LUMICORRECTIONS_ENTRIES_ID" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS_ENTRIES_ID" TO CMS_LUMI_WRITER;
/*=========================LUMICORRECTIONS_REV=======================*/
CREATE TABLE "LUMICORRECTIONS_REV"
(	"DATA_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	 CONSTRAINT "LUMICORRECTIONS_REV_PK" PRIMARY KEY("DATA_ID","REVISION_ID")
);
GRANT SELECT ON "LUMICORRECTIONS_REV" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "LUMICORRECTIONS_REV" TO CMS_LUMI_WRITER;
