/*=========================PIXELLUMIDATA=======================*/
begin execute immediate 'drop table PIXELLUMIDATA';exception when others then null;end;
CREATE TABLE "PIXELLUMIDATA"
(	"DATA_ID" NUMBER(20,0),
	"ENTRY_ID" NUMBER(20,0),
	"ENTRY_NAME" VARCHAR2(56),
	"SOURCE" VARCHAR2(128),
	"RUNNUM" NUMBER(10,0),
	"NOMINALEGEV" BINARY_FLOAT,
	 CONSTRAINT "PIXELLUMIDATA_PK" PRIMARY KEY ("DATA_ID")
)
PARTITION BY RANGE(RUNNUM)
(
PARTITION YEAR2011 VALUES LESS THAN(183338),
PARTITION THEREST VALUES LESS THAN(MAXVALUE)
)
;
GRANT SELECT ON "PIXELLUMIDATA" TO PUBLIC;
/*=========================PIXELLUMIDATA_ID=======================*/
begin execute immediate 'drop table PIXELLUMIDATA_ID';exception when others then null;end;
CREATE TABLE "PIXELLUMIDATA_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "PIXELLUMIDATA_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "PIXELLUMIDATA_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "PIXELLUMIDATA_ID" TO PUBLIC;
/*=========================PIXELLUMIDATA_ENTRIES=======================*/
begin execute immediate 'drop table PIXELLUMIDATA_ENTRIES';exception when others then null;end;
CREATE TABLE "PIXELLUMIDATA_ENTRIES"
(	"ENTRY_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	"NAME" VARCHAR2(56),
	 CONSTRAINT "PIXELLUMIDATA_ENTRIES_PK" PRIMARY KEY ("ENTRY_ID")
);
GRANT SELECT ON "PIXELLUMIDATA_ENTRIES" TO PUBLIC;
/*=========================PIXELLUMIDATA_ENTRIES_ID=======================*/
begin execute immediate 'drop table PIXELLUMIDATA_ENTRIES_ID';exception when others then null;end;
CREATE TABLE "PIXELLUMIDATA_ENTRIES_ID"
(	"NEXTID" NUMBER(20,0),
	 CONSTRAINT "PIXELLUMIDATA_ENTRIES_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "PIXELLUMIDATA_ENTRIES_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "PIXELLUMIDATA_ENTRIES_ID" TO PUBLIC;
/*=========================PIXELLUMIDATA_REV=======================*/
begin execute immediate 'drop table PIXELLUMIDATA_REV';exception when others then null;end;
CREATE TABLE "PIXELLUMIDATA_REV"
(	"DATA_ID" NUMBER(20,0),
	"REVISION_ID" NUMBER(20,0),
	 CONSTRAINT "PIXELLUMIDATA_REV_PK" PRIMARY KEY("DATA_ID","REVISION_ID")
);
GRANT SELECT ON "PIXELLUMIDATA_REV" TO PUBLIC;
/*=========================PIXELLUMISUMMARYV2=======================*/
begin execute immediate 'drop table PIXELLUMISUMMARYV2';exception when others then null;end;
CREATE TABLE "PIXELLUMISUMMARYV2"
(	"DATA_ID" NUMBER(20,0),
	"RUNNUM" NUMBER(10,0),
	"LUMILSNUM" NUMBER(10,0),
	"CMSLSNUM" NUMBER(10,0),
	"INSTLUMI" BINARY_FLOAT,
	"INSTLUMIERROR" BINARY_FLOAT,
	"INSTLUMIQUALITY" NUMBER(5,0),
	"BEAMSTATUS" VARCHAR2(28),
	"BEAMENERGY" BINARY_FLOAT,
	"NUMORBIT" NUMBER(10,0),
	"STARTORBIT" NUMBER(10,0),
	 CONSTRAINT "PIXELLUMISUMMARYV2_PK" PRIMARY KEY ("DATA_ID", "LUMILSNUM"))
PARTITION BY RANGE(DATA_ID)(
PARTITION THEREST VALUES LESS THAN(MAXVALUE)
);
GRANT SELECT ON "PIXELLUMISUMMARYV2" TO PUBLIC;
