/*=========================TAGRUNS=======================*/
CREATE TABLE "TAGRUNS"
(
"TAGID" NUMBER(20,0),
"RUNNUM" NUMBER(10),
"LUMIDATAID" NUMBER(20,0),
"TRGDATAID" NUMBER(20,0),
"HLTDATAID" NUMBER(20,0),
"CREATIONTIME" TIMESTAMP (6),
"COMMENT" VARCHAR2(256),
CONSTRAINT "TAGRUNS_PK" PRIMARY KEY ("TAGID","RUNNUM")
)
PARTITION BY RANGE(RUNNUM)
(
PARTITION YEAR2010 VALUES LESS THAN(153368),
PARTITION YEAR2011 VALUES LESS THAN(183338),
PARTITION THEREST VALUES LESS THAN(MAXVALUE)
);
GRANT SELECT ON "TAGRUNS" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "TAGRUNS" TO CMS_LUMI_WRITER;

CREATE INDEX TAGRUNS_RUNNUM_LOCAL_IDX ON TAGRUNS(RUNNUM) LOCAL;

/*=========================TAGS=======================*/
CREATE TABLE "TAGS"
(	
"TAGNAME" VARCHAR2(128) NOT NULL,
"TAGID" NUMBER(20,0),
 "CREATIONTIME" TIMESTAMP (6),
CONSTRAINT "TAGS_PK" PRIMARY KEY ("TAGID"),
CONSTRAINT "NAME_UNIQUE" UNIQUE ("TAGNAME")
);
GRANT SELECT ON "TAGS" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "TAGS" TO CMS_LUMI_WRITER;

/*=========================TAGS_ID=======================*/
CREATE TABLE "TAGS_ID"
(
"NEXTID"  NUMBER(20,0),
CONSTRAINT "TAGS_ID_PK" PRIMARY KEY ("NEXTID")
);
INSERT INTO "TAGS_ID"("NEXTID") VALUES(0);
GRANT SELECT ON "TAGS_ID" TO PUBLIC;
GRANT SELECT,INSERT,DELETE,UPDATE ON "TAGS_ID" TO CMS_LUMI_WRITER;
